# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# ('.\\patches\\*', 'patches'),  

a = Analysis(['main.py'],
             pathex=['C:\\development\\projects\\gacc\\nfpauto'],
             binaries=[('.\\chromedriver.exe', '.'), ('.\\geckodriver.exe', '.') ],
             datas=[
                 (HOMEPATH + '\\PyQt5\\Qt\\bin\Qt5Core.dll', 'PyQt5\\Qt\\bin'),
                 (HOMEPATH + '\\pyzbar\libiconv.dll', '.'),
                 (HOMEPATH + '\\pyzbar\libzbar-64.dll', '.'),
                 ('.\\windows_dlls\\*', '.'),
                 ('.\\assets\\icons\\*', 'assets\\icons' ),
                 ('.\\assets\\sounds\\*', 'assets\\sounds' ),
                 ('.\\assets\\entidade.jpg', 'assets' ),
                 ('.\\assets\\video_image.png', 'assets' ),
                 ('.\\assets\\video_image_warming.png', 'assets' ),
                 ('.\\styles\\*', 'styles' ),
                 ('.\\clean_database\\*', '.' ),
                 ('.\\seleniumdb\\seleniumdb.db', 'seleniumdb'),                                  
                 ],

             hiddenimports=['numpy.random.common', 'numpy.random.bounded_integers', 'numpy.random.entropy'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[
                 '.\\test',
                 '.\\db',
                 '.\\files_import',
                 '.\\build_scripts',
                 '.\\install-script',
                 'tkinter',
                 'lib2to3',
                 'matplotlib',
                 'mpl-data',                 
                 'pandas',
                 'PIL',
                 'pytz',
                 'scipy',
                 'win32com',
                 'PyQt5.QtHelp',
                 'PyQt5.QtMultimedia',
                 'PyQt5.QtNetwork',
                 'PyQt5.QtOpenGL',
                 'PyQt5.QtPrintSupport',
                 'PyQt5.QtQml',
                 'PyQt5.QtQuick',
                 'PyQt5.QtQuickWidgets',
                 'PyQt5.QtSensors',
                 'PyQt5.QtSerialPort',
                 'PyQt5.QtSql',
                 'PyQt5.QtSvg',
                 'PyQt5.QtTest',
                 'PyQt5.QtXml',
                 ''
                 ],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='NotaAmiga',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          icon='.\\assets\\icons\\favicon.ico' )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='NotaAmiga')
