# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\development\projects\gacc\nfpauto\dialog_postar.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1004, 932)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/ai.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(0.95)
        Dialog.setStyleSheet("")
        self.lista_notas = QtWidgets.QTableWidget(Dialog)
        self.lista_notas.setEnabled(True)
        self.lista_notas.setGeometry(QtCore.QRect(30, 50, 941, 281))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lista_notas.setFont(font)
        self.lista_notas.setStyleSheet("color: rgb(45, 45, 45);")
        self.lista_notas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista_notas.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lista_notas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lista_notas.setGridStyle(QtCore.Qt.DotLine)
        self.lista_notas.setObjectName("lista_notas")
        self.lista_notas.setColumnCount(0)
        self.lista_notas.setRowCount(0)
        self.lista_notas.horizontalHeader().setStretchLastSection(False)
        self.lista_notas.verticalHeader().setVisible(False)
        self.lista_notas.verticalHeader().setHighlightSections(False)
        self.btn_iniciar_postagem = QtWidgets.QPushButton(Dialog)
        self.btn_iniciar_postagem.setGeometry(QtCore.QRect(30, 340, 941, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_iniciar_postagem.setFont(font)
        self.btn_iniciar_postagem.setStyleSheet("color: rgb(45, 45, 45);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/play1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_iniciar_postagem.setIcon(icon1)
        self.btn_iniciar_postagem.setIconSize(QtCore.QSize(64, 64))
        self.btn_iniciar_postagem.setObjectName("btn_iniciar_postagem")
        self.btn_fechar = QtWidgets.QPushButton(Dialog)
        self.btn_fechar.setGeometry(QtCore.QRect(780, 840, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_fechar.setFont(font)
        self.btn_fechar.setStyleSheet("color: rgb(45, 45, 45);")
        self.btn_fechar.setObjectName("btn_fechar")
        self.label_log = QtWidgets.QLabel(Dialog)
        self.label_log.setGeometry(QtCore.QRect(390, 480, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_log.setFont(font)
        self.label_log.setStyleSheet("color: rgb(45, 45, 45);")
        self.label_log.setObjectName("label_log")
        self.list_log = QtWidgets.QListView(Dialog)
        self.list_log.setGeometry(QtCore.QRect(30, 520, 931, 311))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.list_log.setFont(font)
        self.list_log.setStyleSheet("color: rgb(45, 45, 45);")
        self.list_log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_log.setFrameShadow(QtWidgets.QFrame.Plain)
        self.list_log.setLineWidth(1)
        self.list_log.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_log.setProperty("showDropIndicator", False)
        self.list_log.setAlternatingRowColors(True)
        self.list_log.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.list_log.setObjectName("list_log")
        self.btn_limpar = QtWidgets.QPushButton(Dialog)
        self.btn_limpar.setGeometry(QtCore.QRect(750, 480, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_limpar.setFont(font)
        self.btn_limpar.setStyleSheet("color: rgb(45, 45, 45);")
        self.btn_limpar.setObjectName("btn_limpar")
        self.label_log_2 = QtWidgets.QLabel(Dialog)
        self.label_log_2.setGeometry(QtCore.QRect(320, 10, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_log_2.setFont(font)
        self.label_log_2.setStyleSheet("color: rgb(45, 45, 45);")
        self.label_log_2.setObjectName("label_log_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Notas fiscais disponíveis"))
        self.btn_iniciar_postagem.setText(_translate("Dialog", "                              Iniciar Postagem"))
        self.btn_fechar.setText(_translate("Dialog", "Fechar (ESC)"))
        self.label_log.setText(_translate("Dialog", "Log de Atividades"))
        self.btn_limpar.setText(_translate("Dialog", "Limpar Log"))
        self.label_log_2.setText(_translate("Dialog", "Notas Disponíveis para Postagem"))
