# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\development\projects\gacc\nfpauto\dialog_postar.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5.QtGui import QFont, QIcon, QPixmap
from PyQt5.QtCore import Qt, QRect, QSize, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import QAbstractItemView, QTableWidget, QLabel,  QPushButton, QListView, QFrame


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1004, 932)
        font = QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QIcon()
        icon.addPixmap(QPixmap("assets/icons/ai.png"), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(0.95)
        Dialog.setStyleSheet("")
        self.lista_notas = QTableWidget(Dialog)
        self.lista_notas.setEnabled(True)
        self.lista_notas.setGeometry(QRect(30, 50, 941, 281))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lista_notas.setFont(font)
        self.lista_notas.setStyleSheet("color: rgb(45, 45, 45);")
        self.lista_notas.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.lista_notas.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.lista_notas.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.lista_notas.setGridStyle(Qt.DotLine)
        self.lista_notas.setObjectName("lista_notas")
        self.lista_notas.setColumnCount(0)
        self.lista_notas.setRowCount(0)
        self.lista_notas.horizontalHeader().setStretchLastSection(False)
        self.lista_notas.verticalHeader().setVisible(False)
        self.lista_notas.verticalHeader().setHighlightSections(False)
        self.btn_iniciar_postagem = QPushButton(Dialog)
        self.btn_iniciar_postagem.setGeometry(QRect(30, 340, 941, 91))
        font = QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_iniciar_postagem.setFont(font)
        self.btn_iniciar_postagem.setStyleSheet("color: rgb(45, 45, 45);")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("assets/icons/play1.png"), QIcon.Normal, QIcon.Off)
        self.btn_iniciar_postagem.setIcon(icon1)
        self.btn_iniciar_postagem.setIconSize(QSize(64, 64))
        self.btn_iniciar_postagem.setObjectName("btn_iniciar_postagem")
        self.btn_fechar = QPushButton(Dialog)
        self.btn_fechar.setGeometry(QRect(780, 840, 181, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_fechar.setFont(font)
        self.btn_fechar.setStyleSheet("color: rgb(45, 45, 45);")
        self.btn_fechar.setObjectName("btn_fechar")
        self.label_log = QLabel(Dialog)
        self.label_log.setGeometry(QRect(390, 480, 211, 31))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_log.setFont(font)
        self.label_log.setStyleSheet("color: rgb(45, 45, 45);")
        self.label_log.setObjectName("label_log")
        self.list_log = QListView(Dialog)
        self.list_log.setGeometry(QRect(30, 520, 931, 311))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.list_log.setFont(font)
        self.list_log.setStyleSheet("color: rgb(45, 45, 45);")
        self.list_log.setFrameShape(QFrame.StyledPanel)
        self.list_log.setFrameShadow(QFrame.Plain)
        self.list_log.setLineWidth(1)
        self.list_log.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.list_log.setProperty("showDropIndicator", False)
        self.list_log.setAlternatingRowColors(True)
        self.list_log.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.list_log.setObjectName("list_log")
        self.btn_limpar = QPushButton(Dialog)
        self.btn_limpar.setGeometry(QRect(750, 480, 201, 31))
        font = QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_limpar.setFont(font)
        self.btn_limpar.setStyleSheet("color: rgb(45, 45, 45);")
        self.btn_limpar.setObjectName("btn_limpar")
        self.label_log_2 = QLabel(Dialog)
        self.label_log_2.setGeometry(QRect(320, 10, 391, 31))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_log_2.setFont(font)
        self.label_log_2.setStyleSheet("color: rgb(45, 45, 45);")
        self.label_log_2.setObjectName("label_log_2")

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Notas fiscais disponíveis"))
        self.btn_iniciar_postagem.setText(_translate("Dialog", "                              Iniciar Postagem"))
        self.btn_fechar.setText(_translate("Dialog", "Fechar (ESC)"))
        self.label_log.setText(_translate("Dialog", "Log de Atividades"))
        self.btn_limpar.setText(_translate("Dialog", "Limpar Log"))
        self.label_log_2.setText(_translate("Dialog", "Notas Disponíveis para Postagem"))
