# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\development\projects\gacc\nfpauto\login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 324)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setWindowOpacity(0.95)
        self.grupo_login = QtWidgets.QGroupBox(Dialog)
        self.grupo_login.setGeometry(QtCore.QRect(20, 20, 401, 281))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.grupo_login.setFont(font)
        self.grupo_login.setObjectName("grupo_login")
        self.lbl_message_login = QtWidgets.QLabel(self.grupo_login)
        self.lbl_message_login.setGeometry(QtCore.QRect(30, 220, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_message_login.setFont(font)
        self.lbl_message_login.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_message_login.setWordWrap(True)
        self.lbl_message_login.setObjectName("lbl_message_login")
        self.lbl_message_login_2 = QtWidgets.QLabel(self.grupo_login)
        self.lbl_message_login_2.setGeometry(QtCore.QRect(30, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_message_login_2.setFont(font)
        self.lbl_message_login_2.setObjectName("lbl_message_login_2")
        self.lbl_message_login_3 = QtWidgets.QLabel(self.grupo_login)
        self.lbl_message_login_3.setGeometry(QtCore.QRect(30, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_message_login_3.setFont(font)
        self.lbl_message_login_3.setObjectName("lbl_message_login_3")
        self.txt_usuario = QtWidgets.QLineEdit(self.grupo_login)
        self.txt_usuario.setGeometry(QtCore.QRect(120, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setObjectName("txt_usuario")
        self.txt_password = QtWidgets.QLineEdit(self.grupo_login)
        self.txt_password.setGeometry(QtCore.QRect(120, 100, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.txt_password.setFont(font)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_login = QtWidgets.QPushButton(self.grupo_login)
        self.btn_login.setGeometry(QtCore.QRect(20, 160, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_login.setIcon(icon)
        self.btn_login.setIconSize(QtCore.QSize(24, 24))
        self.btn_login.setObjectName("btn_login")
        self.btn_cancel = QtWidgets.QPushButton(self.grupo_login)
        self.btn_cancel.setGeometry(QtCore.QRect(210, 160, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.grupo_login.setTitle(_translate("Dialog", "Login"))
        self.lbl_message_login.setText(_translate("Dialog", "[message]"))
        self.lbl_message_login_2.setText(_translate("Dialog", "Usuário"))
        self.lbl_message_login_3.setText(_translate("Dialog", "Senha"))
        self.txt_usuario.setPlaceholderText(_translate("Dialog", "Digite seu usuário"))
        self.txt_password.setPlaceholderText(_translate("Dialog", "Digite sua senha"))
        self.btn_login.setText(_translate("Dialog", "    Confirmar"))
        self.btn_cancel.setText(_translate("Dialog", "    Sair (ESC)"))
