# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\development\projects\gacc\nfpauto\ui\list.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import QFont, QIcon, QPixmap, QCursor
from PyQt5.QtCore import Qt, QRect, QSize, QMetaObject, QCoreApplication, pyqtSignal, QObject
from PyQt5.QtWidgets import QListView, QToolBox, QFrame, QWidget, QLineEdit, QCheckBox, QTabWidget, QComboBox, QProgressBar, QLabel, QPlainTextEdit, QAbstractItemView, QTableWidget, QGroupBox,  QPushButton, QDialogButtonBox

class Ui_MainWindow(QObject):

    sig_cancelar_video = pyqtSignal(int)
    sig_cancelar = pyqtSignal(int)

    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 700)
        MainWindow.setMaximumSize(QSize(1368, 700))
        font = QFont()
        font.setFamily("Montserrat Light")
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addPixmap(QPixmap("assets/icons/favicon2.png"), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QSize(24, 24))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QRect(10, 10, 1350, 680))
        font = QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QFrame.Panel)
        self.toolBox.setFrameShadow(QFrame.Sunken)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page = QWidget()
        self.page.setGeometry(QRect(0, 0, 1348, 608))
        self.page.setObjectName("page")
        self.btn_login = QPushButton(self.page)
        self.btn_login.setGeometry(QRect(1020, 10, 271, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_login.setFont(font)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("assets/icons/login.png"), QIcon.Normal, QIcon.Off)
        self.btn_login.setIcon(icon1)
        self.btn_login.setIconSize(QSize(32, 32))
        self.btn_login.setObjectName("btn_login")
        self.lbTitulo = QLabel(self.page)
        self.lbTitulo.setGeometry(QRect(20, 10, 210, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbTitulo.setFont(font)
        self.lbTitulo.setObjectName("lbTitulo")
        self.btn_limpa_banco = QPushButton(self.page)
        self.btn_limpa_banco.setGeometry(QRect(1680, 420, 211, 41))
        font = QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_limpa_banco.setFont(font)
        self.btn_limpa_banco.setStyleSheet("hidden: hidden")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap("assets/icons/database.png"), QIcon.Normal, QIcon.Off)
        self.btn_limpa_banco.setIcon(icon2)
        self.btn_limpa_banco.setIconSize(QSize(32, 32))
        self.btn_limpa_banco.setObjectName("btn_limpa_banco")
        self.tableWidget = QTableWidget(self.page)
        self.tableWidget.setGeometry(QRect(20, 50, 601, 521))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(Qt.DotLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.lbl_info = QLabel(self.page)
        self.lbl_info.setGeometry(QRect(20, 565, 591, 45))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_info.setFont(font)
        self.lbl_info.setAutoFillBackground(False)
        self.lbl_info.setStyleSheet("")
        self.lbl_info.setText("")
        self.lbl_info.setObjectName("lbl_info")
        self.lbl_qtde_notas_2 = QLabel(self.page)
        self.lbl_qtde_notas_2.setGeometry(QRect(320, 10, 111, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_qtde_notas_2.setFont(font)
        self.lbl_qtde_notas_2.setObjectName("lbl_qtde_notas_2")
        self.combo_status = QComboBox(self.page)
        self.combo_status.setGeometry(QRect(430, 10, 191, 31))
        font = QFont()
        font.setPointSize(8)
        self.combo_status.setFont(font)
        self.combo_status.setObjectName("combo_status")
        self.btn_cnpj = QPushButton(self.page)
        self.btn_cnpj.setGeometry(QRect(1130, 0, 191, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_cnpj.setFont(font)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap("assets/icons/cnpj.png"), QIcon.Normal, QIcon.Off)
        self.btn_cnpj.setIcon(icon3)
        self.btn_cnpj.setIconSize(QSize(32, 32))
        self.btn_cnpj.setCheckable(False)
        self.btn_cnpj.setChecked(False)
        self.btn_cnpj.setAutoExclusive(False)
        self.btn_cnpj.setAutoDefault(False)
        self.btn_cnpj.setDefault(False)
        self.btn_cnpj.setObjectName("btn_cnpj")
        self.tab_opcao = QTabWidget(self.page)
        self.tab_opcao.setGeometry(QRect(640, 70, 711, 461))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tab_opcao.setFont(font)
        self.tab_opcao.setStyleSheet("")
        self.tab_opcao.setIconSize(QSize(64, 64))
        self.tab_opcao.setObjectName("tab_opcao")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_video = QLabel(self.tab_5)
        self.label_video.setGeometry(QRect(50, 60, 591, 361))
        self.label_video.setFrameShape(QFrame.Box)
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.btn_video = QPushButton(self.tab_5)
        self.btn_video.setGeometry(QRect(50, 10, 591, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_video.setFont(font)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap("assets/icons/qrcode2.png"), QIcon.Normal, QIcon.Off)
        self.btn_video.setIcon(icon4)
        self.btn_video.setIconSize(QSize(24, 24))
        self.btn_video.setObjectName("btn_video")
        self.tab_opcao.addTab(self.tab_5, "")
        self.tab = QWidget()
        self.tab.setObjectName("tab")
        self.grupo_chave_completa = QGroupBox(self.tab)
        self.grupo_chave_completa.setGeometry(QRect(20, 90, 661, 201))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.grupo_chave_completa.setFont(font)
        self.grupo_chave_completa.setObjectName("grupo_chave_completa")
        self.txtChave = QPlainTextEdit(self.grupo_chave_completa)
        self.txtChave.setGeometry(QRect(30, 70, 591, 51))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txtChave.setFont(font)
        self.txtChave.setToolTipDuration(3)
        self.txtChave.setAutoFillBackground(False)
        self.txtChave.setStyleSheet("")
        self.txtChave.setPlainText("")
        self.txtChave.setBackgroundVisible(False)
        self.txtChave.setCenterOnScroll(False)
        self.txtChave.setPlaceholderText("")
        self.txtChave.setObjectName("txtChave")
        self.lblChave = QLabel(self.grupo_chave_completa)
        self.lblChave.setGeometry(QRect(30, 30, 151, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblChave.setFont(font)
        self.lblChave.setObjectName("lblChave")
        self.lblDigitos = QLabel(self.grupo_chave_completa)
        self.lblDigitos.setGeometry(QRect(200, 160, 311, 20))
        font = QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblDigitos.setFont(font)
        self.lblDigitos.setText("")
        self.lblDigitos.setObjectName("lblDigitos")
        self.tab_opcao.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName("tab_2")
        self.grupo_chave_completa_2 = QGroupBox(self.tab_2)
        self.grupo_chave_completa_2.setGeometry(QRect(20, 60, 661, 311))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.grupo_chave_completa_2.setFont(font)
        self.grupo_chave_completa_2.setObjectName("grupo_chave_completa_2")
        self.txtChave_2 = QPlainTextEdit(self.grupo_chave_completa_2)
        self.txtChave_2.setEnabled(False)
        self.txtChave_2.setGeometry(QRect(30, 100, 321, 51))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txtChave_2.setFont(font)
        self.txtChave_2.setAutoFillBackground(False)
        self.txtChave_2.setPlainText("")
        self.txtChave_2.setBackgroundVisible(False)
        self.txtChave_2.setCenterOnScroll(False)
        self.txtChave_2.setPlaceholderText("")
        self.txtChave_2.setObjectName("txtChave_2")
        self.lblChave_2 = QLabel(self.grupo_chave_completa_2)
        self.lblChave_2.setGeometry(QRect(30, 60, 241, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblChave_2.setFont(font)
        self.lblChave_2.setObjectName("lblChave_2")
        self.lblDigitos_2 = QLabel(self.grupo_chave_completa_2)
        self.lblDigitos_2.setGeometry(QRect(30, 160, 311, 20))
        font = QFont()
        font.setFamily("Montserrat Alternates Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblDigitos_2.setFont(font)
        self.lblDigitos_2.setText("")
        self.lblDigitos_2.setObjectName("lblDigitos_2")
        self.txtChave_3 = QPlainTextEdit(self.grupo_chave_completa_2)
        self.txtChave_3.setGeometry(QRect(370, 100, 231, 51))
        font = QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txtChave_3.setFont(font)
        self.txtChave_3.setAutoFillBackground(False)
        self.txtChave_3.setPlainText("")
        self.txtChave_3.setBackgroundVisible(False)
        self.txtChave_3.setCenterOnScroll(False)
        self.txtChave_3.setPlaceholderText("")
        self.txtChave_3.setObjectName("txtChave_3")
        self.btn_estab = QPushButton(self.grupo_chave_completa_2)
        self.btn_estab.setGeometry(QRect(30, 200, 311, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_estab.setFont(font)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap("assets/icons/shop.png"), QIcon.Normal, QIcon.Off)
        self.btn_estab.setIcon(icon5)
        self.btn_estab.setIconSize(QSize(24, 24))
        self.btn_estab.setObjectName("btn_estab")
        self.tab_opcao.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName("tab_3")
        self.grupo_chave_completa_3 = QGroupBox(self.tab_3)
        self.grupo_chave_completa_3.setGeometry(QRect(40, 110, 621, 201))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.grupo_chave_completa_3.setFont(font)
        self.grupo_chave_completa_3.setObjectName("grupo_chave_completa_3")
        self.txt_arquivo = QPlainTextEdit(self.grupo_chave_completa_3)
        self.txt_arquivo.setEnabled(False)
        self.txt_arquivo.setGeometry(QRect(10, 50, 371, 51))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txt_arquivo.setFont(font)
        self.txt_arquivo.setAutoFillBackground(False)
        self.txt_arquivo.setPlainText("")
        self.txt_arquivo.setBackgroundVisible(False)
        self.txt_arquivo.setCenterOnScroll(False)
        self.txt_arquivo.setPlaceholderText("")
        self.txt_arquivo.setObjectName("txt_arquivo")
        self.lblDigitos_3 = QLabel(self.grupo_chave_completa_3)
        self.lblDigitos_3.setGeometry(QRect(10, 170, 581, 20))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblDigitos_3.setFont(font)
        self.lblDigitos_3.setText("")
        self.lblDigitos_3.setObjectName("lblDigitos_3")
        self.btn_arquivo = QPushButton(self.grupo_chave_completa_3)
        self.btn_arquivo.setGeometry(QRect(400, 50, 191, 41))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_arquivo.setFont(font)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap("assets/icons/folder.png"), QIcon.Normal, QIcon.Off)
        self.btn_arquivo.setIcon(icon6)
        self.btn_arquivo.setIconSize(QSize(24, 24))
        self.btn_arquivo.setObjectName("btn_arquivo")
        self.btn_importar = QPushButton(self.grupo_chave_completa_3)
        self.btn_importar.setGeometry(QRect(10, 110, 581, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_importar.setFont(font)
        icon7 = QIcon()
        icon7.addPixmap(QPixmap("assets/icons/up.png"), QIcon.Normal, QIcon.Off)
        self.btn_importar.setIcon(icon7)
        self.btn_importar.setIconSize(QSize(32, 32))
        self.btn_importar.setObjectName("btn_importar")
        self.check_dir = QCheckBox(self.grupo_chave_completa_3)
        self.check_dir.setGeometry(QRect(420, 20, 181, 20))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.check_dir.setFont(font)
        self.check_dir.setObjectName("check_dir")
        self.tab_opcao.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName("tab_4")
        self.grupo_chave_completa_4 = QGroupBox(self.tab_4)
        self.grupo_chave_completa_4.setGeometry(QRect(20, 50, 671, 311))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.grupo_chave_completa_4.setFont(font)
        self.grupo_chave_completa_4.setObjectName("grupo_chave_completa_4")
        self.btn_portal = QPushButton(self.grupo_chave_completa_4)
        self.btn_portal.setGeometry(QRect(30, 200, 601, 41))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_portal.setFont(font)
        icon8 = QIcon()
        icon8.addPixmap(QPixmap("assets/icons/refresh.png"), QIcon.Normal, QIcon.Off)
        self.btn_portal.setIcon(icon8)
        self.btn_portal.setIconSize(QSize(32, 32))
        self.btn_portal.setObjectName("btn_portal")
        self.barra_progresso_portal = QProgressBar(self.grupo_chave_completa_4)
        self.barra_progresso_portal.setGeometry(QRect(30, 250, 601, 23))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.barra_progresso_portal.setFont(font)
        self.barra_progresso_portal.setProperty("value", 0)
        self.barra_progresso_portal.setTextVisible(False)
        self.barra_progresso_portal.setInvertedAppearance(False)
        self.barra_progresso_portal.setObjectName("barra_progresso_portal")
        self.lbl_cnpj_estab = QLabel(self.grupo_chave_completa_4)
        self.lbl_cnpj_estab.setGeometry(QRect(20, 40, 221, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_cnpj_estab.setFont(font)
        self.lbl_cnpj_estab.setObjectName("lbl_cnpj_estab")
        self.lbl_qtde_notas = QLabel(self.grupo_chave_completa_4)
        self.lbl_qtde_notas.setGeometry(QRect(50, 110, 181, 41))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_qtde_notas.setFont(font)
        self.lbl_qtde_notas.setObjectName("lbl_qtde_notas")
        self.txt_cnpj_estab = QLineEdit(self.grupo_chave_completa_4)
        self.txt_cnpj_estab.setGeometry(QRect(240, 40, 261, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txt_cnpj_estab.setFont(font)
        self.txt_cnpj_estab.setObjectName("txt_cnpj_estab")
        self.txt_num_notas = QLineEdit(self.grupo_chave_completa_4)
        self.txt_num_notas.setGeometry(QRect(240, 110, 61, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txt_num_notas.setFont(font)
        self.txt_num_notas.setText("")
        self.txt_num_notas.setMaxLength(3)
        self.txt_num_notas.setAlignment(Qt.AlignCenter)
        self.txt_num_notas.setPlaceholderText("")
        self.txt_num_notas.setObjectName("txt_num_notas")
        self.tab_opcao.addTab(self.tab_4, "")
        self.lbl_message = QLabel(self.page)
        self.lbl_message.setGeometry(QRect(20, 565, 591, 45))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_message.setFont(font)
        self.lbl_message.setAutoFillBackground(False)
        self.lbl_message.setStyleSheet("")
        self.lbl_message.setText("")
        self.lbl_message.setObjectName("lbl_message")
        self.label = QLabel(self.page)
        self.label.setGeometry(QRect(1630, 900, 261, 16))
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_stat = QPushButton(self.page)
        self.btn_stat.setGeometry(QRect(930, 0, 191, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_stat.setFont(font)
        icon9 = QIcon()
        icon9.addPixmap(QPixmap("assets/icons/report.png"), QIcon.Normal, QIcon.Off)
        self.btn_stat.setIcon(icon9)
        self.btn_stat.setIconSize(QSize(32, 32))
        self.btn_stat.setObjectName("btn_stat")
        self.grupo_atalhos = QGroupBox(self.page)
        self.grupo_atalhos.setGeometry(QRect(640, 530, 701, 71))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.grupo_atalhos.setFont(font)
        self.grupo_atalhos.setObjectName("grupo_atalhos")
        self.lbl_atalho1 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1.setGeometry(QRect(20, 0, 291, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1.setFont(font)
        self.lbl_atalho1.setObjectName("lbl_atalho1")
        self.lbl_atalho1_2 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_2.setGeometry(QRect(220, 0, 231, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_2.setFont(font)
        self.lbl_atalho1_2.setObjectName("lbl_atalho1_2")
        self.lbl_atalho1_3 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_3.setGeometry(QRect(20, 20, 301, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_3.setFont(font)
        self.lbl_atalho1_3.setObjectName("lbl_atalho1_3")
        self.lbl_atalho1_4 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_4.setGeometry(QRect(340, 20, 111, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_4.setFont(font)
        self.lbl_atalho1_4.setObjectName("lbl_atalho1_4")
        self.lbl_atalho1_5 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_5.setGeometry(QRect(480, 20, 161, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_5.setFont(font)
        self.lbl_atalho1_5.setObjectName("lbl_atalho1_5")
        self.lbl_atalho1_6 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_6.setGeometry(QRect(480, 0, 181, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_6.setFont(font)
        self.lbl_atalho1_6.setObjectName("lbl_atalho1_6")
        self.lbl_atalho1_7 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_7.setGeometry(QRect(20, 40, 141, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_7.setFont(font)
        self.lbl_atalho1_7.setObjectName("lbl_atalho1_7")
        self.lbl_atalho1_8 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_8.setGeometry(QRect(20, 340, 591, 71))
        font = QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_8.setFont(font)
        self.lbl_atalho1_8.setObjectName("lbl_atalho1_8")
        self.lbl_atalho1_9 = QLabel(self.grupo_atalhos)
        self.lbl_atalho1_9.setGeometry(QRect(480, 40, 121, 41))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_atalho1_9.setFont(font)
        self.lbl_atalho1_9.setObjectName("lbl_atalho1_9")
        self.btn_postar = QPushButton(self.page)
        self.btn_postar.setGeometry(QRect(730, 0, 191, 51))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.btn_postar.setFont(font)
        self.btn_postar.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_postar.setToolTipDuration(3)
        self.btn_postar.setStyleSheet("")
        icon10 = QIcon()
        icon10.addPixmap(QPixmap("assets/icons/ai.png"), QIcon.Normal, QIcon.Off)
        self.btn_postar.setIcon(icon10)
        self.btn_postar.setIconSize(QSize(40, 40))
        self.btn_postar.setCheckable(False)
        self.btn_postar.setChecked(False)
        self.btn_postar.setAutoExclusive(False)
        self.btn_postar.setAutoDefault(False)
        self.btn_postar.setDefault(False)
        self.btn_postar.setFlat(False)
        self.btn_postar.setObjectName("btn_postar")
        self.toolBox.addItem(self.page, icon4, "")
        self.page_2 = QWidget()
        self.page_2.setGeometry(QRect(0, 0, 1348, 608))
        self.page_2.setObjectName("page_2")
        self.list_log = QListView(self.page_2)
        self.list_log.setGeometry(QRect(20, 490, 1311, 91))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.list_log.setFont(font)
        self.list_log.setStyleSheet("color: rgb(45, 45, 45);")
        self.list_log.setFrameShape(QFrame.StyledPanel)
        self.list_log.setFrameShadow(QFrame.Plain)
        self.list_log.setLineWidth(1)
        self.list_log.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.list_log.setProperty("showDropIndicator", False)
        self.list_log.setAlternatingRowColors(True)
        self.list_log.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.list_log.setObjectName("list_log")
        self.label_log_2 = QLabel(self.page_2)
        self.label_log_2.setGeometry(QRect(20, 10, 301, 31))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_log_2.setFont(font)
        self.label_log_2.setStyleSheet("color: rgb(45, 45, 45);")
        self.label_log_2.setObjectName("label_log_2")
        self.lista_notas = QTableWidget(self.page_2)
        self.lista_notas.setEnabled(True)
        self.lista_notas.setGeometry(QRect(20, 40, 1311, 331))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lista_notas.setFont(font)
        self.lista_notas.setStyleSheet("color: rgb(45, 45, 45);")
        self.lista_notas.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.lista_notas.setSelectionMode(QAbstractItemView.MultiSelection)
        self.lista_notas.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.lista_notas.setGridStyle(Qt.SolidLine)
        self.lista_notas.setWordWrap(False)
        self.lista_notas.setObjectName("lista_notas")
        self.lista_notas.setColumnCount(0)
        self.lista_notas.setRowCount(0)
        self.lista_notas.horizontalHeader().setStretchLastSection(False)
        self.lista_notas.verticalHeader().setVisible(False)
        self.lista_notas.verticalHeader().setHighlightSections(False)
        self.btn_fechar = QPushButton(self.page_2)
        self.btn_fechar.setGeometry(QRect(1730, 720, 181, 71))
        font = QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_fechar.setFont(font)
        self.btn_fechar.setStyleSheet("color: rgb(45, 45, 45);")
        self.btn_fechar.setObjectName("btn_fechar")
        self.btn_limpar = QPushButton(self.page_2)
        self.btn_limpar.setGeometry(QRect(1130, 450, 201, 31))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_limpar.setFont(font)
        self.btn_limpar.setStyleSheet("color: rgb(45, 45, 45);")
        self.btn_limpar.setObjectName("btn_limpar")
        self.label_log = QLabel(self.page_2)
        self.label_log.setGeometry(QRect(20, 460, 161, 31))
        font = QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_log.setFont(font)
        self.label_log.setStyleSheet("color: rgb(45, 45, 45);")
        self.label_log.setObjectName("label_log")
        self.btn_iniciar_postagem = QPushButton(self.page_2)
        self.btn_iniciar_postagem.setGeometry(QRect(20, 380, 1311, 61))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_iniciar_postagem.setFont(font)
        self.btn_iniciar_postagem.setStyleSheet("color: rgb(45, 45, 45);")
        icon11 = QIcon()
        icon11.addPixmap(QPixmap("assets/icons/play1.png"), QIcon.Normal, QIcon.Off)
        self.btn_iniciar_postagem.setIcon(icon11)
        self.btn_iniciar_postagem.setIconSize(QSize(32, 32))
        self.btn_iniciar_postagem.setObjectName("btn_iniciar_postagem")
        icon12 = QIcon()
        icon12.addPixmap(QPixmap("assets/icons/ai.png"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.page_2, icon12, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(5)
        self.tab_opcao.setCurrentIndex(4)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nota Amiga - Aplicação do Cliente"))
        self.btn_login.setText(_translate("MainWindow", "     Login no Portal Amigo"))
        self.lbTitulo.setText(_translate("MainWindow", "Cupons disponíveis"))
        self.btn_limpa_banco.setToolTip(_translate("MainWindow", "<h2>\n"
" Este comando elimina as notas já postadas \n"
"</h2>"))
        self.btn_limpa_banco.setText(_translate("MainWindow", "   Limpar Banco (Notas Já Processadas)"))
        self.lbl_qtde_notas_2.setText(_translate("MainWindow", "Filtrar por Status:"))
        self.btn_cnpj.setToolTip(_translate("MainWindow", "<h2>Clique aqui para atualizar o CNPJ da entidade</h2>"))
        self.btn_cnpj.setText(_translate("MainWindow", "Minha Entidade"))
        self.btn_video.setText(_translate("MainWindow", "    Iniciar Captura"))
        self.tab_opcao.setTabText(self.tab_opcao.indexOf(self.tab_5), _translate("MainWindow", "Captura por Câmera"))
        self.grupo_chave_completa.setTitle(_translate("MainWindow", "Utilize o leitor de código de barras ou digite a chave de acesso"))
        self.txtChave.setToolTip(_translate("MainWindow", "Digite a Chave de Acesso Aqui"))
        self.lblChave.setText(_translate("MainWindow", "Chave de Acesso"))
        self.tab_opcao.setTabText(self.tab_opcao.indexOf(self.tab), _translate("MainWindow", "&Usar Leitor de Código de Barras"))
        self.grupo_chave_completa_2.setTitle(_translate("MainWindow", "Digitar 5 ultimos subgrupos"))
        self.txtChave_2.setToolTip(_translate("MainWindow", "Digite a Chave de Acesso Aqui"))
        self.lblChave_2.setText(_translate("MainWindow", "Chave de Acesso (parcial)"))
        self.txtChave_3.setToolTip(_translate("MainWindow", "Digite os ultimos 5 subgrupos da chave aqui"))
        self.btn_estab.setText(_translate("MainWindow", "   Selecionar Estabelecimentos"))
        self.tab_opcao.setTabText(self.tab_opcao.indexOf(self.tab_2), _translate("MainWindow", "&Digitar "))
        self.grupo_chave_completa_3.setTitle(_translate("MainWindow", "Buscar Arquivo"))
        self.txt_arquivo.setToolTip(_translate("MainWindow", "Digite a Chave de Acesso Aqui"))
        self.btn_arquivo.setText(_translate("MainWindow", "   Buscar Arquivo"))
        self.btn_importar.setText(_translate("MainWindow", "     Importar"))
        self.check_dir.setText(_translate("MainWindow", "Modo Diretório XMLs"))
        self.tab_opcao.setTabText(self.tab_opcao.indexOf(self.tab_3), _translate("MainWindow", "Importar Arquivo"))
        self.grupo_chave_completa_4.setTitle(_translate("MainWindow", "Clique no botão abaixo para buscar chaves de acesso disponíveis no Portal Amigo"))
        self.btn_portal.setText(_translate("MainWindow", "      Baixar Chaves de Acesso"))
        self.lbl_cnpj_estab.setText(_translate("MainWindow", "CNPJ do Estabelecimento"))
        self.lbl_qtde_notas.setText(_translate("MainWindow", "Quantidade de Notas"))
        self.tab_opcao.setTabText(self.tab_opcao.indexOf(self.tab_4), _translate("MainWindow", "Baixar notas do Portal"))
        self.label.setText(_translate("MainWindow", "<div>Icons made by <a href=\"https://www.flaticon.com/authors/icongeek26\" title=\"Icongeek26\">Icongeek26</a> from <a href=\"https://www.flaticon.com/\"             title=\"Flaticon\">www.flaticon.com</a></div>"))
        self.btn_stat.setText(_translate("MainWindow", "      Ver Estatísticas"))
        self.grupo_atalhos.setTitle(_translate("MainWindow", "Teclas de Atalhos"))
        self.lbl_atalho1.setText(_translate("MainWindow", "ESC - limpa campo de chave"))
        self.lbl_atalho1_2.setText(_translate("MainWindow", "A - Captura por Leitor de Código de Barras"))
        self.lbl_atalho1_3.setText(_translate("MainWindow", "B - Captura por Digitação da Chave (5 últimos grupos)"))
        self.lbl_atalho1_4.setText(_translate("MainWindow", "C - Importar Arquivo"))
        self.lbl_atalho1_5.setText(_translate("MainWindow", "D - Buscar do Portal Amigo"))
        self.lbl_atalho1_6.setText(_translate("MainWindow", "E - Atualizar CNPJ da instituição"))
        self.lbl_atalho1_7.setText(_translate("MainWindow", "L - Fazer Login no Portal"))
        self.lbl_atalho1_8.setText(_translate("MainWindow", "P - Postar no ambiente do governo"))
        self.lbl_atalho1_9.setText(_translate("MainWindow", "V - Captura por Vídeo"))
        self.btn_postar.setToolTip(_translate("MainWindow", "<H2>\n"
"  Clique aqui para iniciar a postagem automática no site da Nota Fiscal Paulista\n"
"</H2>"))
        self.btn_postar.setText(_translate("MainWindow", "     Iniciar Postagem"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "      Coletor de Notas"))
        self.label_log_2.setText(_translate("MainWindow", "Notas Disponíveis para Postagem"))
        self.btn_fechar.setText(_translate("MainWindow", "Fechar (ESC)"))
        self.btn_limpar.setText(_translate("MainWindow", "Limpar Log"))
        self.label_log.setText(_translate("MainWindow", "Log de Atividades"))
        self.btn_iniciar_postagem.setText(_translate("MainWindow", "                              Iniciar Postagem"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "      Postagem de Notas"))
