# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\development\projects\gacc\nfpauto\update.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 211)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Montserrat Light")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/favicon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_message = QtWidgets.QLabel(self.centralwidget)
        self.lbl_message.setGeometry(QtCore.QRect(20, 140, 921, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_message.setFont(font)
        self.lbl_message.setAutoFillBackground(False)
        self.lbl_message.setStyleSheet("")
        self.lbl_message.setObjectName("lbl_message")
        self.grupo_atalhos = QtWidgets.QGroupBox(self.centralwidget)
        self.grupo_atalhos.setGeometry(QtCore.QRect(1190, 490, 631, 351))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.grupo_atalhos.setFont(font)
        self.grupo_atalhos.setObjectName("grupo_atalhos")
        self.lbl_atalho1 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1.setGeometry(QtCore.QRect(20, 30, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1.setFont(font)
        self.lbl_atalho1.setObjectName("lbl_atalho1")
        self.lbl_atalho1_2 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_2.setGeometry(QtCore.QRect(20, 70, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_2.setFont(font)
        self.lbl_atalho1_2.setObjectName("lbl_atalho1_2")
        self.lbl_atalho1_3 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_3.setGeometry(QtCore.QRect(20, 110, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_3.setFont(font)
        self.lbl_atalho1_3.setObjectName("lbl_atalho1_3")
        self.lbl_atalho1_4 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_4.setGeometry(QtCore.QRect(20, 150, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_4.setFont(font)
        self.lbl_atalho1_4.setObjectName("lbl_atalho1_4")
        self.lbl_atalho1_5 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_5.setGeometry(QtCore.QRect(20, 190, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_5.setFont(font)
        self.lbl_atalho1_5.setObjectName("lbl_atalho1_5")
        self.lbl_atalho1_6 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_6.setGeometry(QtCore.QRect(20, 230, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_6.setFont(font)
        self.lbl_atalho1_6.setObjectName("lbl_atalho1_6")
        self.lbl_atalho1_7 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_7.setGeometry(QtCore.QRect(20, 270, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_7.setFont(font)
        self.lbl_atalho1_7.setObjectName("lbl_atalho1_7")
        self.lbl_atalho1_8 = QtWidgets.QLabel(self.grupo_atalhos)
        self.lbl_atalho1_8.setGeometry(QtCore.QRect(20, 310, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_atalho1_8.setFont(font)
        self.lbl_atalho1_8.setObjectName("lbl_atalho1_8")
        self.btn_cnpj = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cnpj.setGeometry(QtCore.QRect(1610, 10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_cnpj.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/cnpj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cnpj.setIcon(icon1)
        self.btn_cnpj.setIconSize(QtCore.QSize(32, 32))
        self.btn_cnpj.setCheckable(False)
        self.btn_cnpj.setChecked(False)
        self.btn_cnpj.setAutoExclusive(False)
        self.btn_cnpj.setAutoDefault(False)
        self.btn_cnpj.setDefault(False)
        self.btn_cnpj.setObjectName("btn_cnpj")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(1330, 10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_login.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_login.setIcon(icon2)
        self.btn_login.setIconSize(QtCore.QSize(32, 32))
        self.btn_login.setObjectName("btn_login")
        self.btn_limpa_banco = QtWidgets.QPushButton(self.centralwidget)
        self.btn_limpa_banco.setGeometry(QtCore.QRect(1520, 380, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_limpa_banco.setFont(font)
        self.btn_limpa_banco.setStyleSheet("hidden: hidden")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/icons/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_limpa_banco.setIcon(icon3)
        self.btn_limpa_banco.setIconSize(QtCore.QSize(32, 32))
        self.btn_limpa_banco.setObjectName("btn_limpa_banco")
        self.btn_postar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_postar.setGeometry(QtCore.QRect(10, 60, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_postar.setFont(font)
        self.btn_postar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_postar.setToolTipDuration(3)
        self.btn_postar.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/icons/ai.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_postar.setIcon(icon4)
        self.btn_postar.setIconSize(QtCore.QSize(40, 40))
        self.btn_postar.setCheckable(False)
        self.btn_postar.setChecked(False)
        self.btn_postar.setAutoExclusive(False)
        self.btn_postar.setAutoDefault(False)
        self.btn_postar.setDefault(False)
        self.btn_postar.setFlat(False)
        self.btn_postar.setObjectName("btn_postar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 920, 261, 16))
        self.label.setObjectName("label")
        self.lbl_qtde_notas_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_qtde_notas_2.setGeometry(QtCore.QRect(30, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_qtde_notas_2.setFont(font)
        self.lbl_qtde_notas_2.setObjectName("lbl_qtde_notas_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nota Amiga - Aplicação do Cliente"))
        self.lbl_message.setText(_translate("MainWindow", "dsdsdsdsddddddddddddddddddddd"))
        self.grupo_atalhos.setTitle(_translate("MainWindow", "Teclas de Atalhos"))
        self.lbl_atalho1.setText(_translate("MainWindow", "ESC - limpa campo de chave"))
        self.lbl_atalho1_2.setText(_translate("MainWindow", "A - Captura por Leitor de Código de Barras"))
        self.lbl_atalho1_3.setText(_translate("MainWindow", "B - Captura por Digitação da Chave (5 últimos grupos)"))
        self.lbl_atalho1_4.setText(_translate("MainWindow", "C - Importar Arquivo"))
        self.lbl_atalho1_5.setText(_translate("MainWindow", "D - Buscar do Portal Amigo"))
        self.lbl_atalho1_6.setText(_translate("MainWindow", "E - Atualizar CNPJ da instituição"))
        self.lbl_atalho1_7.setText(_translate("MainWindow", "L - Fazer Login no Portal"))
        self.lbl_atalho1_8.setText(_translate("MainWindow", "P - Postar no ambiente do governo"))
        self.btn_cnpj.setToolTip(_translate("MainWindow", "<h2>Clique aqui para atualizar o CNPJ da entidade</h2>"))
        self.btn_cnpj.setText(_translate("MainWindow", "Minha Entidade"))
        self.btn_login.setText(_translate("MainWindow", "     Login no Portal Amigo"))
        self.btn_limpa_banco.setToolTip(_translate("MainWindow", "<h2>\n"
" Este comando elimina as notas já postadas \n"
"</h2>"))
        self.btn_limpa_banco.setText(_translate("MainWindow", "   Limpar Banco (Notas Já Processadas)"))
        self.btn_postar.setToolTip(_translate("MainWindow", "<H2>\n"
"  Clique aqui para iniciar a postagem automática no site da Nota Fiscal Paulista\n"
"</H2>"))
        self.btn_postar.setText(_translate("MainWindow", "      Iniciar Postagem de Notas"))
        self.label.setText(_translate("MainWindow", "<div>Icons made by <a href=\"https://www.flaticon.com/authors/icongeek26\" title=\"Icongeek26\">Icongeek26</a> from <a href=\"https://www.flaticon.com/\"             title=\"Flaticon\">www.flaticon.com</a></div>"))
        self.lbl_qtde_notas_2.setText(_translate("MainWindow", "Filtrar por Status:"))
